//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoreRG
{
    using System;
    using System.Collections.Generic;
    
    public partial class PedidosItens
    {
        public int IdPedidoItens { get; set; }
        public int IdPedido { get; set; }
        public int ProductID { get; set; }
        public short Quantidade { get; set; }
        public decimal PrecoUnitario { get; set; }
    }
}
