//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoreRG
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShoppingCart
    {
        public ShoppingCart()
        {
            this.ShoppingCartItens = new HashSet<ShoppingCartItens>();
        }
    
        public int CartId { get; set; }
        public System.DateTime Data { get; set; }
        public bool IsCheckedOut { get; set; }
    
        public virtual ICollection<ShoppingCartItens> ShoppingCartItens { get; set; }
    }
}
