//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoreRG
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShoppingCartItens
    {
        public int CartItemId { get; set; }
        public int CartId { get; set; }
        public int ProductID { get; set; }
        public System.DateTime Data { get; set; }
        public short Quantidade { get; set; }
    
        public virtual Products Products { get; set; }
        public virtual ShoppingCart ShoppingCart { get; set; }
    }
}
